name: myFirstWorkflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@v3
      - name: config_env
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: display_jdk_version
        run: java --version
      - name: display_mvn_version
        run: mvn --version
      - name: run_code
        run: mvn spring-boot:run