name: myFirstWorkflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@v3
      - name: config_env
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: display_jdk_version
        run: java --version
      - name: display_mvn_version
        run: mvn --version
      - name: print_current_directory
        run: echo "${{github.workspace}}"